### ISSUE TITLE
PvP mods not loading in BGs

### ISSUE THREAD

**Issue by Robocannon** [DeadlyBossMods/DBM-PvP#7] opened 2019-12-16 10:07 UTC
**Twitch client installed classic/retail version on retail/classic**
DBM - PvP Mods r76-classic

**Describe the bug**
No notifications, no timers, nothing loads in battlegrounds. When joining battleground, get a message that PvP mods has loaded but no DBM timers or alerts show. Also get spammed with "You are not in a raid" and "You are not in a party" messages. Have removed and reinstalled both DBM core and PvP mods - same problem.

**Do you have an error log of what happened?**
No error log. Will work on getting one.

**To Reproduce**
Join a battleground

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Not running ElvUI. DBM works fine in dungeons/raids.

**Which version of DeadlyBossMods are you using?**
1.13.24-classic

**Comment by MysticalOS** [comment] 2019-12-16 13:17
The not in party not in raid messages are caused by other addons that have poor syncing code, not related to DBM

As for PVP mods, they aren't done yet. still very WIP. closing ticket as there is alerady an active ticket discussing pvp mods here: https://github.com/DeadlyBossMods/DBM-PvP/issues/5

**Closed by MysticalOS** 2019-12-16 13:17 UTC
