### ISSUE TITLE
Rag Combat countdown timer no longer shows

### ISSUE THREAD

**Issue by chrispphillips** [DeadlyBossMods/DBM-PvP#11] opened 2020-01-03 16:34 UTC
Since updating to the most recent version: DBM-Core-1.13.26-classic the timer to alert players when combat on the Ragnaros encounter is going to start no longer displays.

Was not an issue prior to most recent update. Other players have confirmed same issue after updating. Guildmate who hasn't updated in a while does not have this problem.

**Comment by MysticalOS** [comment] 2020-01-03 20:07
Not sure how this relates to pvp mods, but I looked into the code changes and found the cause, it'll be fixed in next classic update.

**Closed by MysticalOS** 2020-01-03 20:07 UTC
